### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by nevrome** [ISAAKiel/calibrator#1]
I just tried to make calibrator on `Ubuntu 18.04.5 LTS x86_64`, with `GNU Make 4.1` and `g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0` and get the following error:

```bash
$ make
 build/uncal_date_list.o build/main.o build/cal_date_list.o build/sigma_range.o build/uncal_date.o build/cal_curve.o build/cal_date.o
 g++ -O2 -g -Wall -std=c++11 -fmessage-length=0 -I ~/boost -c -o build/main.o src/main.cpp
In file included from src/../include/sigma_range.h:22:0,
                 from src/../include/cal_date.h:23,
                 from src/../include/uncal_date.h:23,
                 from src/main.cpp:13:
src/../include/json.hpp: In function ‘bool nlohmann::operator<(nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType>::const_reference, nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType>::const_reference)’:
src/../include/json.hpp:5539:62: error: wrong number of template arguments (1, should be 2)
                     return *lhs.m_value.array < *rhs.m_value.array;
                                                              ^~~~~
In file included from src/../include/json.hpp:33:0,
                 from src/../include/sigma_range.h:22,
                 from src/../include/cal_date.h:23,
                 from src/../include/uncal_date.h:23,
                 from src/main.cpp:13:
/usr/include/c++/7/array:94:12: note: provided for ‘template<class _Tp, long unsigned int _Nm> struct std::array’
     struct array
            ^~~~~
Makefile:23: recipe for target 'build/main.o' failed
make: *** [build/main.o] Error 1
```

It did work for me in the past on another system, so I assume it's some sort of dependency issue? Any ideas, @MartinHinz?

**Comment by MartinHinz** [comment]
Yeah, probably it is! Referring to the json library: https://github.com/nlohmann/json. Will check it out asap.

**Comment by MartinHinz** [comment]
updated json library, some housekeeping, now it should compile. Please check!

**Comment by nevrome** [comment]
Cool, Martin. Thanks! Compilation works now. Unfortunately I get a segfault when I try to run a simple calibration. 

```bash
$ ./bin/calibrator -b 5000 -s 50
Segmentation fault (core dumped)
```
Am I doing something wrong? Or did the update break something? `-h` works and shows the help text.

**Comment by MartinHinz** [comment]
Thank you! Need to check that on my linux machine, will try to do this today.

**Comment by MartinHinz** [comment]
Please try to run the same command within the bin folder (so, obviously, without the ./bin/ part):

```
cd bin
./calibrator -b 5000 -s 50
```

Does this have any (positive) effect?

**Comment by nevrome** [comment]
Wow - yeah - that works. Why that?

**Comment by MartinHinz** [comment]
Goooood Question? probably something related to the input parser? Although, if you give a date, there should be no dependency to the current Working Directory? Need to figure out, but wanted to make sure that is not only because of my system here... Any suggestions appreciated!

**Comment by nevrome** [comment]
Hm - maybe something related to the calcurve data file?

What is the structure of the input file, btw. I want to test if currycarbon stands ANY chance regarding speed.

**Comment by nevrome** [comment]
Nevermind - found the test data in /bin. A bit unusual to store it there, right?

**Comment by MartinHinz** [comment]
Probably. Wanted to make sure that validation of functionality is easily accessible. Any suggestions where this could go instead? /inst?

**Comment by MartinHinz** [comment]
Please keep me updated which calibration tool get the pool position ;-)

**Comment by nevrome** [comment]
Maybe /examples or /test_data? :man_shrugging:

**Comment by nevrome** [comment]
Wait - calibrator only returns a 5 year resolution. That's a crucial difference. If I did this as well, I'm sure I could bring the runtime down a lot!

**Comment by MartinHinz** [comment]
identified source of error: the cal curve is loaded at runtime. path is relative. As minimum solution I added a error handling for this case in 4fa3b3f. Long term it should be possible to add arbitrary cal curve files? Will make another issue for this (#2), do you think we can close this one than?

**Comment by nevrome** [comment]
Ja - it's solved. Thanks Martin
